---
defaults: &defaults
  appname:     iqt-teamcity-test

dev:
  database: iqt_dev_db
  host: 'localhost'
  <<: *defaults

test:
  database: iqt_test_db
  host: 'localhost'
  <<: *defaults
  
acc:
  database: iqt_acc_db
  host: '192.168.1.2'
  <<: *defaults

prod:
  database: iqt_prod_db
  host: '192.168.1.3'
  <<: *defaults